

INSERT INTO Language (Name, DisplayName, Description) VALUES
('c', 'C', 'General-purpose procedural programming language.'),
('cpp', 'C++', 'General-purpose language with object-oriented and generic features.'),
('csharp', 'C#', 'Multi-paradigm language developed by Microsoft.'),
('java', 'Java', 'Object-oriented language used in enterprise and mobile development.'),
('javascript', 'JavaScript', 'Scripting language for web development.'),
('typescript', 'TypeScript', 'Typed superset of JavaScript.'),
('python', 'Python', 'High-level general-purpose programming language.'),
('ruby', 'Ruby', 'Dynamic, open source language with a focus on simplicity.'),
('php', 'PHP', 'Server-side scripting language for web development.'),
('go', 'Go', 'Compiled language designed at Google (Golang).'),
('rust', 'Rust', 'Systems programming language focused on safety and performance.'),
('swift', 'Swift', 'Apple’s language for iOS and macOS development.'),
('kotlin', 'Kotlin', 'Modern language targeting the JVM and Android.'),
('objective-c', 'Objective-C', 'Language for macOS and iOS development before Swift.'),
('scala', 'Scala', 'JVM language blending OOP and functional programming.'),
('perl', 'Perl', 'General-purpose language well-suited for text processing.'),
('r', 'R', 'Statistical computing and graphics language.'),
('dart', 'Dart', 'Language optimized for client-side applications, developed by Google.'),
('haskell', 'Haskell', 'Purely functional programming language.'),
('elixir', 'Elixir', 'Dynamic functional language built on the Erlang VM.'),
('erlang', 'Erlang', 'Language for highly concurrent and fault-tolerant systems.'),
('lua', 'Lua', 'Lightweight embeddable scripting language.'),
('bash', 'Bash', 'Unix shell and command language.'),
('powershell', 'PowerShell', 'Task automation and configuration management language.'),
('shell', 'Shell', 'Generic shell scripting language.'),
('sql', 'SQL', 'Language for managing data in relational databases.'),
('plsql', 'PL/SQL', 'Oracle’s procedural extension to SQL.'),
('tcl', 'Tcl', 'Scripting language often used for embedded systems.'),
('fsharp', 'F#', 'Functional-first language on the .NET platform.'),
('vbnet', 'VB.NET', 'Multi-paradigm language on the .NET platform.'),
('matlab', 'MATLAB', 'Language for numerical computing.'),
('groovy', 'Groovy', 'Agile dynamic language for the JVM.'),
('julia', 'Julia', 'High-performance language for technical computing.'),
('nim', 'Nim', 'Compiled language with Python-like syntax.'),
('fortran', 'Fortran', 'Language for numerical and scientific computing.'),
('cobol', 'COBOL', 'Language for business, finance, and administrative systems.'),
('ada', 'Ada', 'Language designed for reliability and maintainability.'),
('assembly', 'Assembly', 'Low-level programming language.'),
('vhdl', 'VHDL', 'Hardware description language for FPGA and ASIC design.'),
('verilog', 'Verilog', 'Hardware description language used in electronic design automation.'),
('sas', 'SAS', 'Statistical analysis system language.'),
('abap', 'ABAP', 'Language for programming SAP applications.'),
('apex', 'Apex', 'Salesforce development language.'),
('smalltalk', 'Smalltalk', 'Object-oriented, dynamically typed reflective language.'),
('clojure', 'Clojure', 'Modern dialect of Lisp for the JVM.'),
('common-lisp', 'Common Lisp', 'General-purpose dialect of Lisp.'),
('scheme', 'Scheme', 'Minimalist dialect of Lisp.'),
('prolog', 'Prolog', 'Logic programming language.'),
('ocaml', 'OCaml', 'General-purpose functional language.'),
('mercury', 'Mercury', 'Functional logic programming language.'),
('vbscript', 'VBScript', 'Scripting language based on Visual Basic.'),
('actionscript', 'ActionScript', 'Language for Adobe Flash applications.'),
('racket', 'Racket', 'Lisp/Scheme-based general-purpose programming language.'),
('elm', 'Elm', 'Functional language for frontend web development.'),
('reason', 'Reason', 'Syntax extension and toolchain for OCaml.'),
('crystal', 'Crystal', 'Compiled language with Ruby-like syntax.'),
('d', 'D', 'Systems programming language combining C-like performance with modern syntax.'),
('fth', 'Forth', 'Stack-based procedural language.'),
('v', 'V', 'Simple, fast, safe compiled language.'),
('zig', 'Zig', 'Low-level systems programming language.'),
('solidity', 'Solidity', 'Smart contract language for Ethereum.'),
('vyper', 'Vyper', 'Ethereum smart contract language with strong security focus.'),
('sml', 'SML', 'Standard ML functional programming language.'),
('awk', 'AWK', 'Text-processing language.'),
('sed', 'Sed', 'Stream editor language for filtering and transforming text.'),
('max', 'Max', 'Visual programming language for music and multimedia.'),
('scratch', 'Scratch', 'Block-based visual programming language.'),
('labview', 'LabVIEW', 'Graphical programming language for data acquisition and instrument control.'),
('postscript', 'PostScript', 'Page description language used in the printing process.'),
('opencl', 'OpenCL', 'Language for parallel programming across heterogeneous systems.'),
('glsl', 'GLSL', 'Shader language for OpenGL.'),
('haxe', 'Haxe', 'High-level language that can compile to multiple targets.'),
('purescript', 'PureScript', 'Strongly-typed functional programming language that compiles to JavaScript.');
